on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'
      - uses: actions/cache@v3
        id: cache
        with:
          key: "${{ steps.time.outputs.time }}"
          path: .cache
      - run: yarn
      - run: yarn fetch
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
